CREATE TABLE dbo.DetalheVotacaoSecao_2022_SP_Bruta (
    DT_GERACAO VARCHAR(100),
    HH_GERACAO VARCHAR(100),
    ANO_ELEICAO VARCHAR(100),
    CD_TIPO_ELEICAO VARCHAR(100),
    NM_TIPO_ELEICAO VARCHAR(100),
    NR_TURNO VARCHAR(100),
    CD_ELEICAO VARCHAR(100),
    DS_ELEICAO VARCHAR(100),
    DT_ELEICAO VARCHAR(100),
    TP_ABRANGENCIA VARCHAR(100),
    SG_UF VARCHAR(100),
    SG_UE VARCHAR(100),
    NM_UE VARCHAR(100),
    CD_MUNICIPIO VARCHAR(100),
    NM_MUNICIPIO VARCHAR(100),
    NR_ZONA VARCHAR(100),
    NR_SECAO VARCHAR(100),
    CD_CARGO VARCHAR(100),
    DS_CARGO VARCHAR(100),
    QT_APTOS VARCHAR(100),
    QT_COMPARECIMENTO VARCHAR(100),
    QT_ABSTENCOES VARCHAR(100),
    QT_VOTOS_NOMINAIS VARCHAR(100),
    QT_VOTOS_BRANCOS VARCHAR(100),
    QT_VOTOS_NULOS VARCHAR(100),
    QT_VOTOS_LEGENDA VARCHAR(100),
    QT_VOTOS_ANULADOS_APU_SEP VARCHAR(100),
    NR_LOCAL_VOTACAO VARCHAR(100),
    NM_LOCAL_VOTACAO VARCHAR(100),
    DS_LOCAL_VOTACAO_ENDERECO VARCHAR(100),
    DT_RECEBIMENTO_BU_HOR_TSE VARCHAR(100),
    DT_PRIM_TOT_PARCIAL_HOR_TSE VARCHAR(100),
    DS_ORIGEM_VOTO VARCHAR(100),
    ST_SECAO_INSTALADA VARCHAR(100),
    ST_SECAO_ANULADA VARCHAR(100),
    CD_MODELO_URNA VARCHAR(100),
    DS_MODELO_URNA VARCHAR(100)
);

TRUNCATE TABLE dbo.DetalheVotacaoSecao_2022_SP_Bruta;


BULK INSERT dbo.DetalheVotacaoSecao_2022_SP_Bruta
FROM 'C:\Innovation-Lab---Applied-BI\CSV - TSE\detalhe_votacao_secao_2022_SP.csv'
WITH (
    FIELDTERMINATOR = ';',
    ROWTERMINATOR = '\n',
    FIRSTROW = 2,
    CODEPAGE = 'ACP', 
    TABLOCK
);


IF OBJECT_ID('dbo.Staging_DetalheVotacaoSecao_2022_SP', 'U') IS NOT NULL
    DROP TABLE dbo.Staging_DetalheVotacaoSecao_2022_SP;

WITH Detalhe_Numerado AS (
    SELECT
        -- Chaves limpas
        REPLACE(ANO_ELEICAO, '"', '') AS ANO_ELEICAO,
        REPLACE(NR_TURNO, '"', '') AS NR_TURNO,
        REPLACE(CD_MUNICIPIO, '"', '') AS CD_MUNICIPIO,
        REPLACE(NR_ZONA, '"', '') AS NR_ZONA,
        REPLACE(NR_SECAO, '"', '') AS NR_SECAO,
        REPLACE(CD_CARGO, '"', '') AS CD_CARGO,
        REPLACE(NR_LOCAL_VOTACAO, '"', '') AS NR_LOCAL_VOTACAO,

        -- Textos limpos
        UPPER(TRIM(REPLACE(NM_MUNICIPIO, '"', ''))) AS NM_MUNICIPIO,
        UPPER(TRIM(REPLACE(NM_LOCAL_VOTACAO, '"', ''))) AS NM_LOCAL_VOTACAO,
        UPPER(TRIM(REPLACE(DS_LOCAL_VOTACAO_ENDERECO, '"', ''))) AS DS_LOCAL_VOTACAO_ENDERECO,

        -- Conversão Matemática
        TRY_CAST(TRIM(REPLACE(QT_APTOS, '"', '')) AS INT) AS QT_APTOS,
        TRY_CAST(TRIM(REPLACE(QT_COMPARECIMENTO, '"', '')) AS INT) AS QT_COMPARECIMENTO,
        TRY_CAST(TRIM(REPLACE(QT_ABSTENCOES, '"', '')) AS INT) AS QT_ABSTENCOES,
        TRY_CAST(TRIM(REPLACE(QT_VOTOS_NOMINAIS, '"', '')) AS INT) AS QT_VOTOS_NOMINAIS,
        TRY_CAST(TRIM(REPLACE(QT_VOTOS_BRANCOS, '"', '')) AS INT) AS QT_VOTOS_BRANCOS,
        TRY_CAST(TRIM(REPLACE(QT_VOTOS_NULOS, '"', '')) AS INT) AS QT_VOTOS_NULOS,
        TRY_CAST(TRIM(REPLACE(QT_VOTOS_LEGENDA, '"', '')) AS INT) AS QT_VOTOS_LEGENDA,

        -- Deduplicação
        ROW_NUMBER() OVER (
            PARTITION BY NR_TURNO, CD_MUNICIPIO, NR_ZONA, NR_SECAO, CD_CARGO
            ORDER BY (SELECT NULL)
        ) AS RN
    FROM dbo.DetalheVotacaoSecao_2022_SP_Bruta
)
SELECT 
    ANO_ELEICAO, NR_TURNO, CD_MUNICIPIO, NM_MUNICIPIO, NR_ZONA, NR_SECAO, 
    NR_LOCAL_VOTACAO, NM_LOCAL_VOTACAO, DS_LOCAL_VOTACAO_ENDERECO, CD_CARGO,
    ISNULL(QT_APTOS, 0) AS QT_APTOS,
    ISNULL(QT_COMPARECIMENTO, 0) AS QT_COMPARECIMENTO,
    ISNULL(QT_ABSTENCOES, 0) AS QT_ABSTENCOES,
    ISNULL(QT_VOTOS_NOMINAIS, 0) AS QT_VOTOS_NOMINAIS,
    ISNULL(QT_VOTOS_BRANCOS, 0) AS QT_VOTOS_BRANCOS,
    ISNULL(QT_VOTOS_NULOS, 0) AS QT_VOTOS_NULOS,
    ISNULL(QT_VOTOS_LEGENDA, 0) AS QT_VOTOS_LEGENDA
INTO dbo.Staging_DetalheVotacaoSecao_2022_SP
FROM Detalhe_Numerado
WHERE RN = 1;

